/**
 * GitHub API에서 사용자 커밋을 분석하여 AI 기여 비율을 계산한다.
 *
 * AI 기여 판별 기준:
 * - Co-authored-by 헤더에 AI 관련 키워드
 * - 커밋 메시지에 AI 관련 키워드
 */

const AI_COAUTHOR_PATTERNS = [
  /co-authored-by:.*claude/i,
  /co-authored-by:.*copilot/i,
  /co-authored-by:.*chatgpt/i,
  /co-authored-by:.*openai/i,
  /co-authored-by:.*anthropic/i,
  /co-authored-by:.*cursor/i,
  /co-authored-by:.*codex/i,
  /co-authored-by:.*gemini/i,
  /co-authored-by:.*windsurf/i,
  /co-authored-by:.*codeium/i,
  /co-authored-by:.*aider/i,
];

const AI_MESSAGE_PATTERNS = [
  /\bai[- ]generated\b/i,
  /\bai[- ]assisted\b/i,
  /\bgenerated by (claude|copilot|chatgpt|cursor|codex|gemini)/i,
  /\bvia (claude|copilot|chatgpt|cursor|codex|gemini)/i,
];

export async function analyzeAIContributions(username, options = {}) {
  const { token, maxRepos = 30, maxCommitsPerRepo = 100 } = options;

  const headers = {
    "Accept": "application/vnd.github+json",
    "User-Agent": "github-ai-stat",
  };
  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }

  // 사용자의 최근 레포 가져오기
  const reposRes = await fetch(
    `https://api.github.com/users/${username}/repos?sort=pushed&per_page=${maxRepos}`,
    { headers }
  );
  if (!reposRes.ok) throw new Error(`Failed to fetch repos for ${username}`);
  const repos = await reposRes.json();

  let totalCommits = 0;
  let aiCommits = 0;
  const toolCounts = {};

  for (const repo of repos) {
    if (repo.fork) continue;

    try {
      const commitsRes = await fetch(
        `https://api.github.com/repos/${repo.full_name}/commits?author=${username}&per_page=${maxCommitsPerRepo}`,
        { headers }
      );
      if (!commitsRes.ok) continue;
      const commits = await commitsRes.json();

      for (const commit of commits) {
        const message = commit.commit?.message || "";
        totalCommits++;

        const isAI = isAIContribution(message);
        if (isAI) {
          aiCommits++;
          const tool = detectTool(message);
          if (tool) {
            toolCounts[tool] = (toolCounts[tool] || 0) + 1;
          }
        }
      }
    } catch {
      // skip repos we can't access
    }
  }

  return {
    totalCommits,
    aiCommits,
    aiCommitRatio: totalCommits > 0 ? aiCommits / totalCommits : 0,
    toolCounts,
  };
}

function isAIContribution(message) {
  for (const pattern of AI_COAUTHOR_PATTERNS) {
    if (pattern.test(message)) return true;
  }
  for (const pattern of AI_MESSAGE_PATTERNS) {
    if (pattern.test(message)) return true;
  }
  return false;
}

function detectTool(message) {
  const lower = message.toLowerCase();
  if (lower.includes("claude code") || lower.includes("claude-code")) return "claude-code";
  if (lower.includes("claude")) return "claude";
  if (lower.includes("copilot")) return "github-copilot";
  if (lower.includes("chatgpt") || lower.includes("openai")) return "chatgpt";
  if (lower.includes("cursor")) return "cursor";
  if (lower.includes("codex")) return "codex";
  if (lower.includes("gemini")) return "gemini";
  if (lower.includes("windsurf") || lower.includes("codeium")) return "windsurf";
  return null;
}
